packages:
  - ./html-hunter
  - ./hunt-client
  - ./hunt-crawler
  - ./hunt-searchengine
  - ./hunt-servant
  - ./hunt-server
  - ./hunt-server-cli
  - ./hunt-test/data/jokes
extra-deps:
  - data-r-tree-0.0.5.0
  - data-stringmap-1.0.1.1
  - hxt-cache-9.1.0.1
  - hxt-xpath-9.1.2.2
resolver: nightly-2016-08-06
